config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "boards#index"
  resources :boards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :users 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :boards
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  # before_action :set_board, :only [:show, :edit]

  def index
    @boards = current_user.boards
  end

  def show
  end

  def new
    @board = Board.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @board = current_user.boards.new(board_params)

    if @board.save
      redirect_to boards_path
    else
      render :new
    end
  end

  private

  def board_params
    params.require(:board).permit(:name)
  end

  def set_board
    @board = Board.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: @board, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :board_title %>
    <%= f.text_field :board_title, class: "input" %>
  </div>
 <%= f.submit nil, class: "ui blue button" %>
<% end %>

app/views/boards/edit.html.erb
<h1>Boards#edit</h1>
<p>Find me in app/views/boards/edit.html.erb</p>

app/views/boards/index.html.erb
<h2>Hello <%= current_user.first_name %></h2><h1> Welcome to Trollo Boards </h1>
<h3>Click a Board To View Content</h3>
<%= link_to 'Create a new board', new_board_path %>
<ul>
  <% @boards.each do |board| %>
    <li><%= link_to board.name, board %></li>
  <% end %>
</ul>

app/views/boards/new.html.erb
<h1>Add A Board</h1>
<%= form_for (@board) do |f| %>
  <%= f.label :name %>
  <%= f.text_area :name, required: true %>

  <%= f.submit %>
<% end %>

app/views/boards/show.html.erb
<h1>Boards#show</h1>
<p>Find me in app/views/boards/show.html.erb</p>

// <%= link_to 'Add Comment', new_board_list_path(@board) %>

app/views/layouts/_navbar.html.erb
<nav class="ui menu">
  <%= link_to "Your Boards", root_path, class: "item" %>
  <%= link_to "Add Boards", new_board_path, class: "item" %>
  <div class="right menu">
    <% if current_user %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "item" %>
    <% else %>
      <%= link_to "Register", new_user_registration_path, class: "item" %>
      <%= link_to "Login", new_user_session_path, class: "item" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trollo1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>